{% set name = "hpp-environments" %}
{% set version = "4.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 077209982e8b8e6c8b45f79d5aa53bf92deed484d18b0830bdf0f521f560b9f2

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - doxygen
  host:
    - boost-cpp
    - example-robot-data
  run:
    - boost-cpp

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}

about:
  home: https://github.com/humanoid-path-planner/{{ name }}
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: {{ name }} subpackage of Humanoid Path Planner suite
  description: |
    HPP (Humanoid Path Planner) is a collection of software packages implementing
    path planning functionalities for a humanoid robot. The core functionalities are well
    suited to solve classical path planning problems. It can be extended to path planning
    for other types of robots like digital actors for instance.
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/humanoid-path-planner/{{ name }}

extra:
  recipe-maintainers:
    - ymontmarin
